alertmanager:
  alertmanagerSpec:
    replicas: 3
  config:
    global:
      resolve_timeout: 5m
      telegram_api_url: "https://api.telegram.org"

    templates:
      - '/etc/alertmanager/*.tmpl'

    receivers:
    - name: blackhole
    - name: telegram-test
      telegram_configs:
        - chat_id: -1002481451909
          bot_token: 7269922966:AAHsF7WvY4m7AFybnrX7lyhGArnVz9osLZI 
          api_url: "https://api.telegram.org"
          send_resolved: true
          parse_mode: HTML
          message: '{{ template "telegram.default" . }}'

    route:
      # group_by: ['ds_id'] # Алерты группируются по UUID кластера.
      # group_wait: 15s
      # group_interval: 30s
      # repeat_interval: 12h
      receiver: telegram-test
      routes:
        - receiver: telegram-test
          continue: true
          matchers:
          - severity="critical"
        - receiver: telegram-test
          matchers:
          - alertname="Watchdog"

additionalPrometheusRulesMap:
  rule-name:
    groups:
      - name: alertmanager
        rules:
          - alert: HostOutOfMemoryTEST
            expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 90) * on(instance) group_left (nodename) node_uname_info{ nodename=~".+" }
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: Host out of memory (instance { { $labels.instance } })
              description: "Node memory is filling up (< 90% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"